name: wp_api
description: A library for WordPress REST API.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0
  woop_api:
    path: ../woop_api

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mockito: ^5.3.2
  test: ^1.19.2
  very_good_analysis: ^3.1.0
