name: woop

packages:
  - /packages/**
  # - /packages/wp_api/
  # - /packages/woop_api/

scripts:
  test:
    run: melos exec flutter test
    description: Run tests
  
  test:dart:
    run: melos exec dart test
    description: Run test in all dart packages
    select-package:
      flutter: false
      dir-exists: test
  generate:
    run: melos exec flutter pub run build_runner build
    description: Run generate files
  generate:dart:
    run: melos exec dart pub run build_runner build
    description: Run generate files