name: woop
description: A Package for Woocommerce and Wordpress API integration.
version: 0.0.1
homepage: null
publish_to: 'none'

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  http: ^0.13.5
  woo:
    path: packages/woo
  wp:
    path: packages/wp

dev_dependencies:
  build_runner: ^2.3.3
  mockito: ^5.3.2
  test: ^1.19.2
  very_good_analysis: ^3.1.0
