name: woo_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  http: ^0.13.5
  woop_api:
    path: ../woop_api

dev_dependencies:
  build_runner: ^2.3.3
  mockito: ^5.3.2
  test: ^1.19.2
  very_good_analysis: ^3.1.0
