// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'woo_product.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_WoopProduct _$$_WoopProductFromJson(Map<String, dynamic> json) =>
    _$_WoopProduct(
      id: json['id'] as int,
      name: json['name'] as String,
      slug: json['slug'] as String,
      permalink: json['permalink'] as String,
      date_created: DateTime.parse(json['date_created'] as String),
      date_created_gmt: DateTime.parse(json['date_created_gmt'] as String),
      date_modified: DateTime.parse(json['date_modified'] as String),
      date_modified_gmt: DateTime.parse(json['date_modified_gmt'] as String),
      type: json['type'] as String,
      status: json['status'] as String,
      featured: json['featured'] as bool,
      catalog_visibility: json['catalog_visibility'] as String,
      description: json['description'] as String,
      short_description: json['short_description'] as String,
      sku: json['sku'] as String,
      price: json['price'] as String,
      regular_price: json['regular_price'] as String,
      sale_price: json['sale_price'] as String,
      date_on_sale_from: json['date_on_sale_from'] == null
          ? null
          : DateTime.parse(json['date_on_sale_from'] as String),
      date_on_sale_from_gmt: json['date_on_sale_from_gmt'] == null
          ? null
          : DateTime.parse(json['date_on_sale_from_gmt'] as String),
      date_on_sale_to: json['date_on_sale_to'] == null
          ? null
          : DateTime.parse(json['date_on_sale_to'] as String),
      date_on_sale_to_gmt: json['date_on_sale_to_gmt'] == null
          ? null
          : DateTime.parse(json['date_on_sale_to_gmt'] as String),
      on_sale: json['on_sale'] as bool,
      purchasable: json['purchasable'] as bool,
      total_sales: json['total_sales'] as int,
      virtual: json['virtual'] as bool,
      downloadable: json['downloadable'] as bool,
      downloads: json['downloads'] as List<dynamic>,
      download_limit: json['download_limit'] as int,
      download_expiry: json['download_expiry'] as int,
      external_url: json['external_url'] as String,
      button_text: json['button_text'] as String,
      tax_status: json['tax_status'] as String,
      tax_class: json['tax_class'] as String,
      manage_stock: json['manage_stock'] as bool,
      stock_quantity: json['stock_quantity'],
      backorders: json['backorders'] as String,
      backorders_allowed: json['backorders_allowed'] as bool,
      backordered: json['backordered'] as bool,
      low_stock_amount: json['low_stock_amount'],
      sold_individually: json['sold_individually'] as bool,
      weight: json['weight'] as String,
      dimensions:
          WooDimensions.fromJson(json['dimensions'] as Map<String, dynamic>),
      shipping_required: json['shipping_required'] as bool,
      shipping_taxable: json['shipping_taxable'] as bool,
      shipping_class: json['shipping_class'] as String,
      shipping_class_id: json['shipping_class_id'] as int,
      reviews_allowed: json['reviews_allowed'] as bool,
      average_rating: json['average_rating'] as String,
      rating_count: json['rating_count'] as int,
      upsell_ids: json['upsell_ids'] as List<dynamic>,
      cross_sell_ids: json['cross_sell_ids'] as List<dynamic>,
      parent_id: json['parent_id'] as int,
      purchase_note: json['purchase_note'] as String,
      categories: (json['categories'] as List<dynamic>)
          .map((e) => WooCategory.fromJson(e as Map<String, dynamic>))
          .toList(),
      tags: json['tags'] as List<dynamic>,
      images: (json['images'] as List<dynamic>)
          .map((e) => WooImage.fromJson(e as Map<String, dynamic>))
          .toList(),
      attributes: (json['attributes'] as List<dynamic>)
          .map((e) => WooAttribute.fromJson(e as Map<String, dynamic>))
          .toList(),
      default_attributes: json['default_attributes'] as List<dynamic>,
      variations: json['variations'] as List<dynamic>,
      grouped_products: json['grouped_products'] as List<dynamic>,
      menu_order: json['menu_order'] as int,
      price_html: json['price_html'] as String,
      related_ids: json['related_ids'] as List<dynamic>,
      meta_data: json['meta_data'] as List<dynamic>,
      stock_status: json['stock_status'] as String,
      has_options: json['has_options'] as bool,
    );

Map<String, dynamic> _$$_WoopProductToJson(_$_WoopProduct instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'slug': instance.slug,
      'permalink': instance.permalink,
      'date_created': instance.date_created.toIso8601String(),
      'date_created_gmt': instance.date_created_gmt.toIso8601String(),
      'date_modified': instance.date_modified.toIso8601String(),
      'date_modified_gmt': instance.date_modified_gmt.toIso8601String(),
      'type': instance.type,
      'status': instance.status,
      'featured': instance.featured,
      'catalog_visibility': instance.catalog_visibility,
      'description': instance.description,
      'short_description': instance.short_description,
      'sku': instance.sku,
      'price': instance.price,
      'regular_price': instance.regular_price,
      'sale_price': instance.sale_price,
      'date_on_sale_from': instance.date_on_sale_from?.toIso8601String(),
      'date_on_sale_from_gmt':
          instance.date_on_sale_from_gmt?.toIso8601String(),
      'date_on_sale_to': instance.date_on_sale_to?.toIso8601String(),
      'date_on_sale_to_gmt': instance.date_on_sale_to_gmt?.toIso8601String(),
      'on_sale': instance.on_sale,
      'purchasable': instance.purchasable,
      'total_sales': instance.total_sales,
      'virtual': instance.virtual,
      'downloadable': instance.downloadable,
      'downloads': instance.downloads,
      'download_limit': instance.download_limit,
      'download_expiry': instance.download_expiry,
      'external_url': instance.external_url,
      'button_text': instance.button_text,
      'tax_status': instance.tax_status,
      'tax_class': instance.tax_class,
      'manage_stock': instance.manage_stock,
      'stock_quantity': instance.stock_quantity,
      'backorders': instance.backorders,
      'backorders_allowed': instance.backorders_allowed,
      'backordered': instance.backordered,
      'low_stock_amount': instance.low_stock_amount,
      'sold_individually': instance.sold_individually,
      'weight': instance.weight,
      'dimensions': instance.dimensions,
      'shipping_required': instance.shipping_required,
      'shipping_taxable': instance.shipping_taxable,
      'shipping_class': instance.shipping_class,
      'shipping_class_id': instance.shipping_class_id,
      'reviews_allowed': instance.reviews_allowed,
      'average_rating': instance.average_rating,
      'rating_count': instance.rating_count,
      'upsell_ids': instance.upsell_ids,
      'cross_sell_ids': instance.cross_sell_ids,
      'parent_id': instance.parent_id,
      'purchase_note': instance.purchase_note,
      'categories': instance.categories,
      'tags': instance.tags,
      'images': instance.images,
      'attributes': instance.attributes,
      'default_attributes': instance.default_attributes,
      'variations': instance.variations,
      'grouped_products': instance.grouped_products,
      'menu_order': instance.menu_order,
      'price_html': instance.price_html,
      'related_ids': instance.related_ids,
      'meta_data': instance.meta_data,
      'stock_status': instance.stock_status,
      'has_options': instance.has_options,
    };
